name: "Deploy"

concurrency:
  group: "deploy"
  cancel-in-progress: true

on:
  push:
    branches:
      - master

permissions:
  contents: write   # allow pushing back to the repo with GITHUB_TOKEN

jobs:
  deploy:
    name: Build & Deploy Plugins
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout source
        uses: actions/checkout@v5
        with:
          path: "src"

      - name: Checkout builds branch
        uses: actions/checkout@v5
        with:
          ref: "build"
          path: "build"

      - name: Setup JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x ./gradlew
          ./gradlew make :generateUpdaterJson

          rm -f $GITHUB_WORKSPACE/build/*.zip
          cp $GITHUB_WORKSPACE/src/plugins/*/build/outputs/*.zip $GITHUB_WORKSPACE/build/
          cp $GITHUB_WORKSPACE/src/build/outputs/updater.json $GITHUB_WORKSPACE/build/

      - name: Push builds branch
        run: |
          cd $GITHUB_WORKSPACE/build
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Build $GITHUB_SHA" || exit 0   # skip if nothing new
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:build
